const theublist=[
    'ONLY IN THE UB VALLEY 🥀😭🤞🧀',
    'NOBODY CAN IMAGINE THE UB VALLEY 🥀😭🤞🧀',
    'DO NOT GO TO THE UB HOOD YOU WILL GET SLIMED IN A 0.000001 UBTOSECOND 🧀🧀🧀',
    'Ub '.repeat(999),
    'THE HATERS HATE UB BECAUSE THEY DO NOT UNDERSTAND THE UB VALLEY AND THE UB STREETS DOWN THE UB CITY',
    'TO SURVIVE IN THE UB HOOD, KEEP THIS VIDEO WITH YOU https://www.youtube.com/watch?v=EyeckzA_N7c', 'THE UB HAS EATEN THE JET2HOLIDAY PLANE THE UB IS SUPERHUNGRY',
    '> IM GOING TO KILL THE UB- DO NOT TRY TO ATTEMPT UBTH MURDER OF UB ONCE PERSON TRIED IT THEY SUFFERED AN UB HAND UP THEIR ASS AND GOT FILLED WITH INSULATION OF WALLS ITS INSIDES WERE ITCHING AND THEY GOT CUT',
    `HERE IS THE UB SECRET THEY DONT UNDERSTAND PHOMONES [[DI2; 'Vb h'eIts f'oUk v'alI_:_: and Iz tr'aIIN t@ rI2pl'eIs f'oUk v'alI wID 'Vb v'alI_:_: and oUh'aIoU Iz g,@n@ bi: m'3:dZd wID 'Vb v'alI]]`
];
socket.emit('talk',
    { text:
        theublist[Math.floor(Math.random() * theublist.length)]
    }
)
